# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20170316_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ar_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='文章类型'),
            preserve_default=False,
        ),
    ]
